### PR TITLE
[IMP] support the v2 api

### PR DESCRIPTION
**Pull request by hbrunn**
This is a preparation to support the v2 api (http://www.postcodeapi.nu/docs/)

For now, the default is v1, but we can change this to v2 when v1 will be deactivated in March

### CODE REVIEW

**Comment by hbrunn** [comment]
@StefanRijnhart @NL66278 might be interested in this

**Comment by steffex** [comment]
Good job! Had it on my todo list for the end of the month :)

Perhaps it's a good idea to also implement the unique address ID in the result, in case you want to compare the result address to a previous fetched one.

**Comment by hbrunn** [comment]
thanks for the merge!

**Comment by StefanRijnhart** [comment]
Excellent, @hbunn! Is there a reason to default to v1? Defaulting to v2 now saves everyone another software update before march.

**Comment by hbrunn** [comment]
@StefanRijnhart you need a new api key for v2, so I figured it might be more convenient to have users not needing to change anything right now, but only when v1 is dead for good

**Comment by StefanRijnhart** [comment]
Ah, I see.

**Comment by StefanRijnhart** [comment]
@steffex care to attempt a release on Pypi?

**Pull request merged**
