### PR TITLE
Add support for Postcode API v3

### LINKED ISSUE #17: Adapt it to use Postcode API v3
Eventually the version 2 of Postcode API will get deprecated, it will need to be updated to allow to use v3.

- API documentation: https://www.postcodeapi.nu/docs/v3/

### PR DESCRIPTION
**Pull request by gdalmau**
Closes #17 

- Adds support for Postcode API v3 https://www.postcodeapi.nu/docs/v3/#operation/lookup
- Keeps support for Postcode API v2 https://www.postcodeapi.nu/docs/v2/
- Deprecates support for Postcode API v1 (if any)

### CODE REVIEW

**Comment by steffex** [comment]
Thanks for your input so far. We should deprecate v1 code wise. This would make it cleaner.

**Comment by gdalmau** [comment]
> Thanks for your input so far. We should deprecate v1 code wise. This would make it cleaner.

@steffex Ready for review. API v3 now forces to send the house number. Since I don't have an API key for the API v2 I couldn't test it and I let it as it is. If there is any other part of the code that should be removed, please let me know :)

**Comment by gdalmau** [comment]
I've added some tests that can be executed with `POSTCODE_API_KEY=<YOUR_API_KEY> python -m unittest tests/test_api.py`

**Comment by steffex** [comment]
@StefanRijnhart want to chip in?

**Comment by steffex** [comment]
@StefanRijnhart i've created a new version (v0.6), could you add it to PyPI?

**Comment by StefanRijnhart** [comment]
What is needed for you to be able to do this? I haven't used this project in more than 5 years ;-)

**Comment by gdalmau** [comment]
@StefanRijnhart you can take a look at here https://packaging.python.org/tutorials/packaging-projects/

**Comment by steffex** [comment]
@StefanRijnhart @gdalmau i've released version 0.6: https://pypi.org/project/pyPostcode/0.6/

**Pull request merged**
